#! /bin/sh

# File: /etc/init.d/delayed_job

### BEGIN INIT INFO
# Provides:          Startup script for delayed_job process
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Delayed job does background processing for a Rails app
# Description:       Delayed job does background processing for a Rails app
### END INIT INFO


N=/etc/init.d/delayed_job
ruby=1.9.2p125
app_root=/home/ubuntu/she-services/current
user=ubuntu
service="delayed_job"

set -e

usage() {
  echo "Usage: $N {start|stop|status|restart|force-reload} <environment>" >&2
  exit 1
}

set -e

#[ -n "$2" ] || usage

#rails_env="$2"
rails_env=staging

interact() {
    op="$1"
    echo "$1ing $service"
    #su - -c "cd $app_root && /usr/bin/env RAILS_ENV=$rails_env rvm $ruby exec bundle exec script/delayed_job $op" $user
    su - -c "cd $app_root && RAILS_ENV=$rails_env bundle exec script/delayed_job $op" $user
}

case "$1" in
    start|stop|status)
        interact "$1"
        ;;
    reload|restart|force-reload)
        interact restart
        ;;
    *)
        usage
        ;;
esac

exit 0