#! /bin/sh

# File: /etc/init.d/redis

### BEGIN INIT INFO
# Provides:          Startup script for Redis Server
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Redis is an open source, advanced key-value store. 
# Description:       Redis is an open source, advanced key-value store. 
### END INIT INFO


# config: /etc/redis.conf
 
PATH=/usr/local/bin:/sbin:/usr/bin:/bin
 
REDISPORT=6379
EXEC=/usr/bin/redis-server
REDIS_CLI=`which redis-cli`
 
PIDFILE=/home/ubuntu/she-services/shared/pids/redis_${REDISPORT}.pid
CONF="/home/ubuntu/she-services/current/config/redis.conf"
 
case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo -n "$PIDFILE exists, process is already running or crashed\n"
        else
                echo -n "Starting Redis server...\n"
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo -n "$PIDFILE does not exist, process is not running\n"
        else
		PID=$(cat $PIDFILE)
                echo -n "Stopping ...\n"
				$REDIS_CLI -p $REDISPORT SHUTDOWN
                while [ -x ${PIDFILE} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
esac