defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: "AKIAJN4RDOCS3ONTP2LA" #<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "uMBKTuITHNImJSs+XUoioT7TH7fQs4+H4DC29Dtm"#"<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  # fog_directory: "meepsweb-assets"
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete 
  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression = true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently = true

development:
  <<: *defaults
  fog_directory: "romneyrate-development"

szehnder:
  <<: *defaults
  fog_directory: "romneyrate-szehnder"

test:
  <<: *defaults

staging:
  <<: *defaults
  fog_directory: "romneyrate-staging"

production:
  <<: *defaults
  fog_directory: "romneyrate-production"
