files: 
  - /home/ubuntu/romneyrating/shared/log/production.log
  - /home/ubuntu/romneyrating/shared/log/reaper.log
  - /home/ubuntu/romneyrating/shared/log/zmq_redis_broker.log
  - /home/ubuntu/romneyrating/shared/log/socketio_redis.log

destination:
  host: logs.papertrailapp.com
  port: 24964   # optional, defaults to 514